name: Peter Armstrong
markdown: redcarpet
paginate: 7
paginate_path: "page:num/"

about:
  name: Peter Armstrong
  display_name: Peter
  email: peteretep@gmail.com
  web: http://peterarmstrong.ie
  twitter: peteretepeter
  company_github: peterOnePageCRM
  personal_github: peteretep
  job: 'Ruby on Rails developer at OnePageCRM.'
  image: '/img/peter.jpg'

image_folder: "img"
default_feature_image: "img/default.jpg"
